exp_name: CIFAR10-ResNet_1
exp_cfg:
  seed: 1

agent: ImageClassifier
agent_cfg:
  input_shape: [3, 32, 32]
  weight_init: kaiming_norm_fanout
  criterion: CrossEntropyLoss
  net:
    name: ResNet
    kwargs:
      num_classes: 10
      phases: [2, 2, 2, 2]
      reductions: [false, true, true, true]
      expansion_rate: 2
      stem_out_channels: 32
      use_stem: true
  optim:
    name: SGD
    kwargs:
      lr: 0.0025
      momentum: .9
      weight_decay: 3.e-3
  
  scheduler:
    name: CosineAnnealingLR
    kwargs:
      T_max: 200
      eta_min: 0


trainer:
  max_epochs: 200
  gpus: 1

model_checkpoint:
  monitor: val_err
  filename: '[ResNet-CIFAR10]-{epoch:02d}-{val_err:.2f}'
  save_top_k: 5
  mode: min
  verbose: true

logger:
  save_dir:
  log_graph: true

data_loader:
  name: CIFAR10
  kwargs:
    root: ~/.torch
    pin_memory: false
    num_workers: 4
    batch_size: 96
    cutout: true
    cutout_length: 8