exp_name: FashionMNIST-MLP
exp_cfg:
  seed: 1

agent: ImageClassifier
agent_cfg:
  input_shape: [784]
  weight_init: kaiming_norm_fanout
  criterion: CrossEntropyLoss
  net:
    name: MultiLayerPerceptron
    kwargs:
      out_features: 10
      backbones: [[784, null], [1022, 0.50631516], [991, 0.43420869], [968, 0.61551537], [811, 0.68938125]]

  optim:
    name: SGD
    kwargs:
      lr: 0.0025
      momentum: .9
      weight_decay: 3.e-3
  
  scheduler:
    name: CosineAnnealingLR
    kwargs:
      T_max: 200
      eta_min: 0


trainer:
  max_epochs: 200
  gpus: 1

model_checkpoint:
  monitor: val_err
  filename: '[MLP-FashionMNIST]-{epoch:02d}-{val_err:.2f}'
  save_top_k: 5
  mode: min
  verbose: true

logger:
  save_dir:
  log_graph: true

data_loader:
  name: FashionMNIST
  kwargs:
    root: ~/.torch
    pin_memory: true
    num_workers: 4
    drop_last: true
    batch_size: 96
    cutout: true
    cutout_length: 8