exp_name: IMDB-RNN_1
exp_cfg:
  seed: 1

agent: RNNSentimentAnalyzer
agent_cfg:
  input_shape: [2000]
  batch_size: 1
  weight_init: kaiming_norm_fanout
  criterion: BCEWithLogitsLoss
  net:
    name: RNN
    kwargs:
      input_dim: 2000
      embedding_dim: 300
      hidden_dim: 300 
      output_dim: 1

  optim:
    name: SGD
    kwargs:
      lr: 0.0025
      momentum: .9
      weight_decay: 3.e-3
  
  scheduler:
    name: CosineAnnealingLR
    kwargs:
      T_max: 200
      eta_min: 0


trainer:
  max_epochs: 200
  gpus: 1
  gradient_clip_val: .5

model_checkpoint:
  monitor: val_err
  filename: '[RNN-IMDB]-{epoch:02d}-{val_err:.2f}'
  save_top_k: 5
  mode: min
  verbose: true

logger:
  save_dir:
  log_graph: true

data_loader:
  name: IMDB
  kwargs:
    batch_size: 64
    root: .data
    num_workers: 4
    pin_memory: true
    input_dim: 2000
    max_len: 200